name: Cache on MacOS

on:
  workflow_dispatch:

jobs:
  deploy:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: 'Use Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: 12.x

      - name: 'Setup cache for node_modules'
        uses: actions/cache@v3
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}-macos

      - name: 'Install packages'
        run: yarn install
